### ISSUE TITLE
meet some errors in 'trainGAN.lua'

### ISSUE THREAD

**Issue by rogerbao** [Guim3/BcGAN#2]
I get the error below on running _th trainGAN.lua_

> /IcGAN/data/data.lua:32: attempt to compare number with nil

and the error of data.lua is in
`9: function data.new(n, dataset_name, opt_)`  
`32: if n > 0 then`

I find that the _n_ in the 'data.lua' equals _nil_, which is defined in trainGAN.lua by _opt.nThreads_
`32: local data = DataLoader.new(opt.nThreads, opt.dataset, opt)`

but i can't find the definition of opt.nThreads in code,then _n_  equals _nil_.
Please suggest what could possibly be wrong.

**Comment by Guim3** [comment]
Thanks for the issue! I completely overlooked this error.

**Comment by LynnHo** [comment]
@rogerbao I solved this problem. Actually, the problem is that the 'list_attr_celeba.txt' file should be placed in ./celebA. @Guim3 I think it should be written in README.md.

**Comment by Guim3** [comment]
I've added this explanation. Thanks!
