### ISSUE TITLE
The Pre-trained CelebA model is gone

### ISSUE THREAD

**Issue by gy321** [Guim3/BcGAN#7]
The resource disappeared. I can not find the Pre-trained CelebA model. Could you please re-upload a new one?

**Comment by Guim3** [comment]
The [link](https://mega.nz/#!nM5xRQLJ!HWyNgz9VNXjGFyQ2ujpVMPyQCTVHnzI64TpFfSfUqCI) works for me at the time of writing this. Please try again and close this issue if you can download it.
