### ISSUE TITLE
Is there python Tensorflow version available? 

### ISSUE THREAD

**Issue by RoyceDavison** [Guim3/BcGAN#9]
Just curious why you chose to implement in Lua, not by Python tensorflow or Pytorch?

**Comment by RoyceDavison** [comment]
Great paper! Very interesting!

**Comment by Guim3** [comment]
The code was ported to Tensorflow a while ago, you can find it here
https://github.com/zhangqianhui/ICGan-tensorflow

> Just curious why you chose to implement in Lua, not by Python tensorflow or Pytorch?

PyTorch started to exist right after I finished the paper :P
